//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITF_WPF_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class userMask
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
